### ISSUE TITLE
Mismatch between column names and column metadata

### ISSUE THREAD

**Issue by dunstone-a** [WEHISCORE/CELSeq-pipeline#2]
Hi Marek,

When beginning the analysis for the [G000187_Bhavana_Yasmin](https://github.com/WEHISCORE/G000187_Bhavana_Yasmin) Treg data I noticed an issue with the column metadata in the following file:
`/stornext/Projects/score/Analyses/G000187_Bhavana_Nayer/results/S000306/CELSeq-pipeline_Treg_mouse/sc_demultiplex/Treg_S1/`. This may be affecting other data sets using the pipeline so Pete suggested I start this issue. 

**Details**

After loading in the object and looking at the column metadata, I noticed that the rownames do not match with the columns, namely the `well_position` column. 

```
sce <- readRDS(here("/stornext/Projects/score/Analyses/G000187_Bhavana_Nayer",
                    "/results/S000306/CELSeq-pipeline_Treg_mouse/sc_demultiplex",
                    "/Treg_S1/sce.rds"))

library(dplyr)
df <- as.data.frame(colData(sce)) %>% 
  select(c("well_position", "sample_type", "sample_name"))
head(df)
#          well_position      sample_type sample_name
# Treg_A10            A3 50 cell minibulk      Sp 1,2
# Treg_A11           A12 50 cell minibulk      Sp 7,8
# Treg_A12            G6 50 cell minibulk         M 2
# Treg_A13            G7 50 cell minibulk         M 2
# Treg_A14            G8 50 cell minibulk         M 2
# Treg_A15            G9 50 cell minibulk        H T2
```

Pete pointed out that the rows of colData are the same as the columns of the count matrix, so this means that the metadata will not be matching correctly with the count data. Therefore, it is very important to fix this before analysing the data further. 

```
identical(colnames(sce), rownames(colData(sce)))
# [1] TRUE
```

I used the following to re-arrange the rows of the colData:

```
new_order <- gsub("Treg_|\\..+", "", rownames(colData(sce)))
all(new_order %in% sce$well_position)
# [1] TRUE
colData(sce) <- colData(sce)[match(new_order, sce$well_position), ]
rownames(colData(sce)) <- paste0("Treg_", new_order)
```

Pete also ran the original fastq files through `scPipe` so we could double check that this transformation was working. I have compared the metadata after re-arranging the rows with the `scPipe` output and they are identical. 

If you could figure out what has caused this to happen in the pipeline that would be great.

Thanks,
Millie

**Comment by mcmero** [comment]
Thanks for raising this Millie. Just had to make sure the row names matched the sample names for the `pheno_data` data frame.
